version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=babydash.jonchiam.com
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=babydash.jonchiam.com
      - LETSENCRYPT_EMAIL=jczjchiam@gmail.com
      - FIREBASE_URL=${FIREBASE_URL}
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    container_name: babydash
    ports:
      - "4000:4000"
    expose:
      - "4000"
    restart: always

networks:
  default:
    external:
      name: nginx-proxy

